name: Release

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC NPM publish
  contents: read

jobs:
  release:
    name: build & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org
          package-manager-cache: false  # never use caching in release builds

      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm publish --access public